### ISSUE TITLE
Crear componente para Footer

### ISSUE THREAD

**Issue by HectorGarayBascur** [HectorGarayBascur/mytinerary-DevsTrip#5]

**Comment by HectorGarayBascur** [comment]
Solo Texto 1
Pueden agregar otra información a criterio de ustedes (dirección, redes sociales, mapa, lo que quieran)

**Comment by juanmoyano123** [comment]
Como **administrador** de la pagina
Quiero que el usuario al llegar al footer tenga acceso por medio de un click, a la siguiente información: redes sociales, teléfono, ubicación geográfica y mail de contacto.
